name:                ssbmbo
version:             0.1.0.0
github:              "kegan-dev/ssbmbo"
license:             BSD3
author:              "Kegan McIlwaine & Finley McIlwaine"
maintainer:          "kegan.mcilwaine@gmail.com"
copyright:           "2021 Kegan McIlwaine & Finley McIlwaine"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kegan-dev/ssbmbo#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- process
- directory

library:
  source-dirs: src

executables:
  ssbmbo-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ssbmbo

tests:
  ssbmbo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ssbmbo
